fix(test): make `//tests:path_test` work on Windows
The test was failing on Windows:
```
FAIL: testDestPathExt (__main__.DestPathTest.testDestPathExt)
AssertionError: '/bar/baz' != 'external/repo\\foo/bar/baz'

FAIL: testDestPathExtWrong (__main__.DestPathTest.testDestPathExtWrong)
AssertionError: 'external/repo/foo/bar/baz' != 'external/repo\\foo/bar/baz'

FAIL: testSafeShortPathExt (__main__.SafeShortPathTest.testSafeShortPathExt)
AssertionError: 'external/repo/foo/bar/baz' != 'external/repo\\foo/bar/baz'

FAIL: testSafeShortPathGenExt (__main__.SafeShortPathTest.testSafeShortPathGenExt)
AssertionError: 'external/repo/foo/bar/baz' != 'external/repo\\foo/bar/baz'

FAIL: testShortPathDirnameExt (__main__.ShortPathDirnameTest.testShortPathDirnameExt)
AssertionError: 'external/repo/foo/bar' != 'external/repo\\foo/bar'

FAIL: testShortPathDirnameGenExt (__main__.ShortPathDirnameTest.testShortPathDirnameGenExt)
AssertionError: 'external/repo/foo/bar' != 'external/repo\\foo/bar'

FAIL: testTopLevelExt (__main__.ShortPathDirnameTest.testTopLevelExt)
AssertionError: 'external/repo' != 'external'
```

The mock `File` class used `os.path.join()` which produces
platform-specific path separators (backslashes on Windows), which
doesn't match Bazel's behavior which always uses forward slashes
regardless of platform:
- use `posixpath.join()` instead,
- enable the test in Windows CI since it now passes.