Show what happens if someone tries to use bazel_skylib and stardoc when bazel_skylib is renamed within your repo.
It fails because the provider is scoped by the name it is loaded through.

$ bazel build rename_skylib_example:my_rule_doc
Analyzing: target //rename_skylib_example:my_rule_doc (0 packages loaded, 0 targets configured)
ERROR: /usr/local/google/home/aiuto/ws/rules_pkg/pkg/rename_skylib_example/BUILD:21:12: in deps attribute of stardoc rule //rename_skylib_example:my_rule_doc: '//rename_skylib_example:my_rule' does not have mandatory providers: 'StarlarkLibraryInfo'
...

$ bazel build rename_skylib_example:dummy
This works, in spite of loading my_bazel_sklib.paths.bzl. We are not
looking at the provider.